name: Deploy aws-whatsapp-sysauto

on:
  push:
    paths:
      - aws-whatsapp-sysauto/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # ✅ necesario para OIDC
      contents: read    # para poder hacer checkout del repo

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 📦 Empaquetar aws-whatsapp-sysauto.zip
        run: |
          cd aws-whatsapp-sysauto
          zip -r ../aws-whatsapp-sysauto.zip .

      - name: 🔐 Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::376572378022:role/Github_link_aws_whatsapp_sysauto
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: 🚀 Subir a Lambda
        run: |
          aws lambda update-function-code \
            --function-name aws-whatsapp-sysauto \
            --zip-file fileb://aws-whatsapp-sysauto.zip \
            --region us-east-2
